name: tntn
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Utility Packages
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.1
  dio: ^5.8.0+1
  http: ^0.13.6  # <-- HTTP package for API requests
  intl: ^0.18.0  # <-- Added intl package for timestamps

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
